on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Kubernetes Network Verification
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python-test
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install z3-solver
          pip install requests
      - name: Verify Network Policy
        run: |
          python ./verify-network-policy.py -control control-policy.yaml -proposed proposed-policy.yaml
